Repository potaje-hub/potaje-hub, pull requests merged in 2024-12, with the labels that each got.

#18 feat: Advance filtering. Merge branch advance filtering into main. Closes: #2 #11
  .github/workflows/commits.yml
  .gitignore
  app/modules/explore/assets/scripts.js
  app/modules/explore/repositories.py
  app/modules/explore/services.py
  app/modules/explore/templates/explore/index.html
  app/modules/explore/tests/__init__.py
  app/modules/explore/tests/test_filterbycombination_selenium.py
  app/modules/explore/tests/test_filterbynumberoffeatures_selenium.py
  app/modules/explore/tests/test_filterbynumberofmodels_selenium.py
  app/modules/explore/tests/test_integration.py
  app/modules/explore/tests/test_unit.py
Labels: enhancement, medium priority

#16 Feat fakenodo
  .github/workflows/flake8.yml
  .github/workflows/pytest.yml
  app/modules/fakenodo/__init__.py
  app/modules/fakenodo/assets/scripts.js
  app/modules/fakenodo/deposition.json
  app/modules/fakenodo/depositions.json
  app/modules/fakenodo/forms.py
  app/modules/fakenodo/models.py
  app/modules/fakenodo/repositories.py
  app/modules/fakenodo/routes.py
  app/modules/fakenodo/seeders.py
  app/modules/fakenodo/services.py
  app/modules/fakenodo/templates/fakenodo/index.html
  app/modules/fakenodo/tests/__init__.py
  app/modules/fakenodo/tests/locustfile.py
  app/modules/fakenodo/tests/test_selenium.py
  app/modules/fakenodo/tests/test_unit.py
  app/modules/notepad/forms.py
  app/modules/notepad/repositories.py
  app/modules/notepad/routes.py
  app/modules/notepad/services.py
  app/modules/notepad/tests/locustfile.py
  app/modules/notepad/tests/test_integration.py
  app/modules/notepad/tests/test_selenium.py
  app/modules/notepad/tests/test_selenium_2.py
  app/modules/notepad/tests/test_unit.py
  app/modules/zenodo/services.py
  docker/docker-compose.dev.yml
Labels: medium priority

#41 fix (telegram_bot): myDatasets function use case fix
  app/modules/telegram_bot/routes.py
Labels: bug

#50 fix (vagrant): CI playbook deletion due to fail
  vagrant/00_main.yml
  vagrant/07_CI.yml
Labels: bug

#48 docs (README.md): vagrant configuration improvement
  README.md
Labels: documentation
